### PR TITLE
use Esri World Geocoding Service for POI and address search

### LINKED ISSUE #44: address search to replace mapzen
hi there! let me know if you need a hand migrating off mapzen's [deprecated](https://mapzen.com/blog/migration/) search service.

I maintain a handy Esri [Leaflet control](https://github.com/Esri/esri-leaflet-geocoder) with really nice [TOU](https://github.com/Esri/esri-leaflet-geocoder#terms-and-conditions) that would be a cinch to plugin.

### PR DESCRIPTION
**Pull request by jgravois**
resolves #44
screenshot 2018-01-17 16 39 53

attribution
screenshot 2018-01-17 16 40 05

cc @hamhands

### CODE REVIEW

**Comment by MrMaksimize** [comment]
Oh!! Excellent!! Sorry I didn't see this sooner.  I'm going to hold off for a few days on taking this - we have a press event tomorrow, but I'll take it after.  

Awesome job and ++ for being a doer!

**Comment by jgravois** [comment]
no worries friend.

API reference: http://esri.github.io/esri-leaflet/api-reference/controls/geosearch.html

live sample: http://esri.github.io/esri-leaflet/examples/geocoding-control.html

**Comment by MrMaksimize** [comment]
Only took me 6 months. But taking this @jgravois!  Will test in staging.  Thank you for the contribution!

**Comment by jgravois** [comment]
no worries! happy to chat more about it if you have any questions.

**Pull request merged**
